fix: instead of moving mill cp and then remove
It looks like there are situations when dealing with mounted drives
you get the following error:

```
Error: EXDEV: cross-device link not permitted, rename '/runner/_work/_temp/9b722d14-6935-45f9-ab1a-526911088cbe' -> '/home/runner/bin/mill'
```

From googling around it looks like we can avoid this by instead
moving the file first and then removing it.

For reference

- https://stackoverflow.com/questions/44146393/error-exdev-cross-device-link-not-permitted-rename-nodejs
- https://github.com/shelljs/shelljs/issues/191

Fixes: #421